### ISSUE TITLE
Problems with Delta2g

### ISSUE THREAD

**Issue by Davidm16** [kaiaai/LDS#1]
I’m not sure how to connect the Delta2g lidar to an ESP32 or how to adapt the code for reading. It doesn’t work for me, help

**Comment by kaiaai** [comment]
Delta-2g needs a little adapter board. Here is the schematic
https://github.com/makerspet/pcb under neato_delta_adapter/output Look for
the 5-pin  Delta-2A/B/G connector, connect TX to TX, GND to GND, MOT+ to
MOT+, MOT- to MOT-, 5V to 5V.

The adapter board connects to the ESP32 breakout board. Here is the
schematic https://github.com/makerspet/pcb/ under esp32_breakout/output .
Connect the 4-pin J3 from the Delta adapter board to the 6-pin LDS
connector on the ESP32 breakout board (same signal names to same signal
names).

As far as code goes, take the lds_basic_esp32 example included with the LDS
library. Change LDS_YDLIDAR_X4 to LDS_DELTA_2G.

Also, look at https://github.com/kaiaai/firmware under kaiaai-esp32 as
another example.

That said, I'm having a problem with Delta-2G. It runs and streams data OK,
bit the captured data shows some fixed pattern noise. I asked 3irobotics
for advice, but there is no answer. I know it can be fixed  because my
Delta-2 dev kit shows a clean picture, but I don't know yet how.

So for the time being, I don't recommend using any Delta-2 LiDARS, not
until this noise gets fixed. Overall, as a developer, I have a negative
impression from using Delta LiDARs - too many problems. Even their main
website https://www.3irobotics.com is down (but the http:// one still
works).

**Comment by Davidm16** [comment]
Okay, I don’t think it’s worth the work of trying to run this lidar to detect just one obstacle that’s my goal. Do you know any cheap lidar that is easy to read with ESP32 or arduino? I just need to know the angle and distance of the sensor accurately

**Comment by kaiaai** [comment]
I have not evaluated LiDAR performance, but as of March 2024 the cheapest - yet easy to connect to ESP32 (no adapter board needed) is LD14P (aka D200 kit) connects directly to ESP32 and seems to work nicely. No adapter board needed. I bought it off AliExpress for $34.30 including shipping.
To connect LD14P to ESP32
- open the [ESP32 board schematic](https://github.com/makerspet/pcb/blob/main/esp32_breakout/output/esp32_breakout_schematic.pdf)
- find the LiDAR connector (J3), note the associated ESP32 pins
- review [LD14P connector pinout](https://www.waveshare.com/wiki/D200_LiDAR_Kit)
- connect 
  - LD14P VCC to 5V
  - LD14P GND to GND
  - LD14P TX to ESP32 GPIO16 (RX)
  - LD14P PWR/RX to ESP32 GPIO17 (TX)

Here is a [blog article](https://kaia.ai/blog/tutorial-connect-ld14p-lidar/) with more details.

HLS-LFCD03 might be another candidate, but it is still in debug.

**Comment by Davidm16** [comment]
Thanks, I’ll try it. With respect to Delta2g its's connected directly to an arduino mega serial I get a data packet of 11 length that does not change any. Should I not be able to read correctly if the engine and driver are properly powered?

**Comment by kaiaai** [comment]
Delta-2G sends the 11 bytes length packet when the rotation speed too slow or too fast. Once you get the speed right, you should start getting long packets with distance data (and thus read it correctly).
